services:
  pm2:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3000:3000"
    environment:
      - SCRIPT_NAME=pm2-start
      - WORKERS=${WORKERS}
    deploy:
      resources:
        reservations:
          cpus: ${WORKERS}
          memory: ${MEM}gb

  watt:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3001:3000"
    environment:
      - SCRIPT_NAME=watt-start
      - WORKERS=${WORKERS}
    deploy:
      resources:
        reservations:
          cpus: ${WORKERS}
          memory: ${MEM}gb
