version: '3.8'

services:
  pm2:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3000:3000"
    environment:
      - SCRIPT_NAME=pm2-start

  watt:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3001:3000"
    environment:
      - SCRIPT_NAME=watt-start

  -3002:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3002:3000"
    environment:
      - SCRIPT_NAME=cluster-start
