name: pm2vswatt

services:
  pm2:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3000:3000"
    environment:
      - SCRIPT_NAME=pm2r-start
      - WORKERS=2
    deploy:
      resources:
        reservations:
          cpus: 2
          memory: 4gb

  watt:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3001:3000"
    environment:
      - SCRIPT_NAME=watt-start
      - WORKERS=2
    deploy:
      resources:
        reservations:
          cpus: 2
          memory: 4gb

  cluster:
    image: platformatic/pm2-vs-watt:latest
    ports:
      - "3002:3000"
    environment:
      - SCRIPT_NAME=cluster-start
      - WORKERS=2
    deploy:
      resources:
        reservations:
          cpus: 2
          memory: 4gb
