FROM node:20-alpine

WORKDIR /app

COPY ./docker/entrypoint.sh /entrypoints/main.sh
RUN chmod +x /entrypoints/main.sh

COPY ./demos/pm2-vs-watt/autocannon.sh /entrypoints/pm2-vs-watt.sh
RUN chmod +x /entrypoints/pm2-vs-watt.sh

RUN npm install -g autocannon && npm cache clean --force

ENV TARGET_URL=http://host.docker.internal
ENV DEMO_NAME=pm2-vs-watt

CMD "/entrypoints/main.sh"
